owner: SpreadSheets600
repo: Uptime-Monitor

sites:
  - name: Cooked Roasted Life Backend
    url: https://cooked-roasted-life.onrender.com
  - name: Portfolio ( Personal Website )
    url: https://spreadsheets600.is-a.dev/
  - name: PoraHobe website
    url: http://dono-03.danbot.host:2521

status-website:
  theme: light
  baseUrl: /Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://spreadsheets600.is-a.dev/Uptime-Monitor/assets/theme.css
  name: Upptime Monitor
  introTitle: My Services And Website Uptime Monitor
  introMessage: Powered By [Upptime](https://upptime.js.org)
  navbar:
    - title: GitHub
      href: https://github.com/spreadsheets600
  i18n:
    footer: SpreadSheets600 // Powered By [Upptime](https://upptime.js.org)
